const API_BASE_URL="https://eventra-backend-aidf.onrender.com/api";
function token(){return localStorage.getItem("eventra_token")||localStorage.getItem("access_token")||sessionStorage.getItem("eventra_token")||sessionStorage.getItem("access_token")||""}
function user(){try{return JSON.parse(localStorage.getItem("eventra_user")||sessionStorage.getItem("eventra_user")||"null")||{} }catch(e){return {}}}
function goBack(){window.location.assign("../../index.html")}
function money(v){return `₦${Math.round(Number(v)||0).toLocaleString("en-NG")}`}
function toast(msg){const t=document.getElementById("toast");if(!t)return;t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2200)}
async function api(path,options={}){const headers={Accept:"application/json",...(options.headers||{})};const t=token();if(t)headers.Authorization=`Bearer ${t}`;const r=await fetch(`${API_BASE_URL}${path}`,{...options,headers});let data={};try{data=await r.json()}catch(_){}if(!r.ok)throw new Error(data?.message||`Request failed (${r.status})`);return data}
function initBack(){document.getElementById("backButton")?.addEventListener("click",goBack)}
function initials(u){return `${(u.first_name||"E")[0]}${(u.last_name||"U")[0]}`.toUpperCase()}

async function initPersonal(){
 const form=document.getElementById("profileForm");if(!form)return;let u=user();
 try{if(token()){const r=await api("/users/profile");u=r?.data?.user||r?.data||r?.user||u}}catch(e){console.warn(e)}
 form.first_name.value=u.first_name||"";form.last_name.value=u.last_name||"";form.email.value=u.email||"";form.phone.value=u.phone||"";form.bio.value=u.bio||"";
 const avatar=document.getElementById("avatar");avatar.textContent=initials(u);if(u.profile_picture_url){avatar.style.backgroundImage=`url("${u.profile_picture_url}")`;avatar.style.backgroundSize="cover";avatar.textContent=""}
 form.addEventListener("submit",async e=>{e.preventDefault();const status=document.getElementById("formStatus");status.textContent="Saving...";try{const payload={first_name:form.first_name.value.trim(),last_name:form.last_name.value.trim(),phone:form.phone.value.trim(),bio:form.bio.value.trim()};const r=await api("/users/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const updated=r?.data?.user||r?.data||r?.user||{...u,...payload};localStorage.setItem("eventra_user",JSON.stringify(updated));status.textContent="Changes saved successfully.";setTimeout(goBack,700)}catch(err){status.textContent=err.message}})
}

function initSecurity(){
 const pass=document.getElementById("passwordForm");if(pass)pass.addEventListener("submit",async e=>{e.preventDefault();const s=document.getElementById("securityStatus");s.textContent="Updating...";try{await api("/users/change-password",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({old_password:pass.old_password.value,new_password:pass.new_password.value})});pass.reset();s.textContent="Password changed successfully."}catch(err){s.textContent=err.message}});
 document.querySelectorAll("[data-switch]").forEach(sw=>{const key=`eventra_2fa_${sw.dataset.switch}`;const on=localStorage.getItem(key)==="1";sw.classList.toggle("on",on);sw.addEventListener("click",()=>{const next=!sw.classList.contains("on");sw.classList.toggle("on",next);localStorage.setItem(key,next?"1":"0");toast(next?`${sw.dataset.switch} enabled locally.`:`${sw.dataset.switch} disabled locally.`)})})
}
function initPrefs(){document.querySelectorAll("[data-pref]").forEach(sw=>{const key=`eventra_pref_${sw.dataset.pref}`;const on=localStorage.getItem(key)!=="0";sw.classList.toggle("on",on);sw.addEventListener("click",()=>{const next=!sw.classList.contains("on");sw.classList.toggle("on",next);localStorage.setItem(key,next?"1":"0")})})}
async function initSaved(){const box=document.getElementById("savedList");if(!box)return;let items=[];try{const r=await api("/wishlist");items=r?.data?.wishlist||r?.data?.items||r?.data||r?.wishlist||[]}catch(e){try{items=JSON.parse(localStorage.getItem("eventra_favourites")||"[]")}catch(_){} }if(!Array.isArray(items))items=[];if(!items.length){box.innerHTML='<div class="empty">No saved events yet.<br><span class="small">Save an event from Discover and it will appear here.</span></div>';return}box.innerHTML=items.map((x,i)=>{const e=x?.Event||x?.event||x;return `<div class="saved-card"><div class="saved-row"><img class="saved-image" src="${e.event_image_url||e.image||"../Event Visual.png"}" onerror="this.style.visibility='hidden'" alt=""><div><div class="saved-title">${e.title||e.name||"Saved Event"}</div><div class="saved-meta">${e.venue_name||e.venue||e.location||"Event location"}<br>${e.start_date?new Date(e.start_date).toLocaleString("en-NG",{dateStyle:"medium",timeStyle:"short"}):"Upcoming event"}</div></div></div></div>`}).join("")}
async function initOrders(){const list=document.getElementById("orders");if(!list)return;let orders=[];try{const r=await api("/bookings");orders=r?.data?.bookings||r?.data?.orders||r?.data||r?.bookings||[]}catch(e){console.warn(e)}if(!Array.isArray(orders))orders=[];if(!orders.length){list.innerHTML='<div class="empty">No orders found yet.</div>';return}list.innerHTML=orders.map(o=>{const ev=o.Event||o.event||{};const status=String(o.status||"pending").toLowerCase();return `<div class="order"><div><div class="order-title">${ev.title||o.event_name||"Event Booking"}</div><div class="order-meta">${ev.start_date?new Date(ev.start_date).toLocaleString("en-NG",{dateStyle:"medium",timeStyle:"short"}):"Event date"}<br>${ev.venue_name||ev.venue_address||"Event venue"}<br>Order #${o.id||"—"}</div></div><div><div class="amount">${money(o.total_price||o.amount||0)}</div><span class="status ${status==="completed"?"green":""}">${status.charAt(0).toUpperCase()+status.slice(1)}</span></div></div>`}).join("")}
function initPayments(){document.getElementById("addPayment")?.addEventListener("click",()=>toast("Payment methods are securely managed by the payment provider."))}
function initHelp(){document.getElementById("supportBtn")?.addEventListener("click",()=>{window.location.href="mailto:support@eventra.com?subject=Eventra%20Support"});document.querySelectorAll("[data-help]").forEach(b=>b.addEventListener("click",()=>toast(`${b.dataset.help} support selected.`)))}

document.addEventListener("DOMContentLoaded",()=>{initBack();const page=document.body.dataset.page;({personal:initPersonal,security:initSecurity,prefs:initPrefs,saved:initSaved,orders:initOrders,payments:initPayments,help:initHelp}[page]||(()=>{}))()})
